### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by oliverpechey** [ollieraikkonen/Freelancer-hd-edition-install-script#22]
1. Download EXE and launch.
2. Select some options and install.
3. Check the game files and ensure that it does exactly what script.xml would have done.
4. Launch the game, check all looks ok.
5. Uninstall, check it deletes everything.
6. Start from step 2 again with different options.

Log any issues found.

**Comment by BC46** [comment]
This is just a todo list for myself:

- [ ] Ensure all options are working as expected
- [ ] Ensure all options with their entries from the mod script are all present
- [ ] Check if all the important explanations from mod_options.rtf are present
