### ISSUE TITLE
Add Offline Install Option

### ISSUE THREAD

**Issue by Drakohen** [ollieraikkonen/Freelancer-hd-edition-install-script#23]
As the title states, a potential for an offline install option would be great for folks that like to archive and also so those that may have limited internet capabilities. The installer doesn't need to come prepackaged with the mod itself but instead, allow for one to point to the zip file while going through the install process.

**Comment by ollieraikkonen** [comment]
Have made this an offline installer. I replaced /debug in the command line with /sourcefile so you can specify a copy of the .zip downloaded from "Releases" on the main github repo. E.g.

`FreelancerHDSetup.exe /sourcefile=C:\freelancerhd.zip`
