### ISSUE TITLE
16:9 Adv Wide Hud not correctly installed

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#25]
![image](https://user-images.githubusercontent.com/45081813/135169343-b29a314e-d1d4-4963-91bf-ca332fe439bb.png)
The installation is almost correct but not quite. The backgrounds for both of the new widgets seem to be missing. We need to make sure that this option has been ported correctly from the FLMM script.

**Comment by BC46** [comment]
Looks like these 2 were forgotten:
```xml
<data file="DATA\INTERFACE\HUD\hud_shipinfo_adv_wide_hud.cmp" method="renamefile" newfilename="DATA\INTERFACE\HUD\hud_shipinfo.cmp" options="9:1">
</data>

<data file="DATA\INTERFACE\HUD\hud_target_adv_wide_hud.cmp" method="renamefile" newfilename="DATA\INTERFACE\HUD\hud_target.cmp" options="9:1">
</data>
```

**Comment by ollieraikkonen** [comment]
Fixed. Note for the future, RenameFile() won't overwrite so the vanilla files need to be renamed first.
