### ISSUE TITLE
Change default destination location

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#26]
![image](https://user-images.githubusercontent.com/45081813/135169547-f1ef1bb5-e6cd-46d0-8a26-a9e2c17d0738.png)
I think the default location should be C:\Program Files (x86)\Microsoft Games\Freelancer HD Edition

**Comment by ollieraikkonen** [comment]
I disagree. Freelancer is notorious for causing problems on Windows 8+ when installing in Program Files. @Drakohen is more aware of the issue than I.

**Comment by BC46** [comment]
Never experienced that before and I've used Windows 8 for over 4 years.

**Comment by ollieraikkonen** [comment]
Let's wait for DF to comment. It might be this was only relevant with FLMM. Can't remember.

**Comment by ollieraikkonen** [comment]
Assuming its fine to make this change

**Comment by ollieraikkonen** [comment]
@BC46 please could you test the following (my Microsoft Games folder is symlinked to another drive so not a good test):

- Rename your current Microsoft Games folder
- Run the installer and check that it creates a Microsoft Games folder

Just want to ensure we cover the scenario where the folder doesnt exist

**Comment by BC46** [comment]
> @BC46 please could you test the following (my Microsoft Games folder is symlinked to another drive so not a good test):
> 
> * Rename your current Microsoft Games folder
> * Run the installer and check that it creates a Microsoft Games folder
> 
> Just want to ensure we cover the scenario where the folder doesnt exist

Just tested it and the installer seems to create the Microsoft Games folder when it doesn't exist. However, we should still revert the default directory location change. According to @Drakohen a Freelancer installation in the PF folder can cause problems if UAC is enabled.

**Comment by ollieraikkonen** [comment]
Change reverted as agreed
