### ISSUE TITLE
New file host

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#29]
My download speed dropped from 20 MB/s to 11 MB/s during the installation proces. This leads me to believe that GitHub is not the most reliable host for downloading large files. We should consider using a different file host if possible.

It's not that important though as the current host is still fine, just the download speeds are inconsistent.

**Comment by ollieraikkonen** [comment]
This will need to be a file host that allows us to "hotlink" the file. i.e. It does not have a verification screen or a catchpa. For this reason Google Drive is out. I wonder if OneDrive would work. Needs further investigation.

Assigning the 0.5 milestone.

**Comment by BC46** [comment]
Uploaded 0.4.1 to OneDrive https://1drv.ms/u/s!Aq3RdxuD3TvwhddND2sAn9ZzxfKUqg?e=CdGdrs

**Comment by Drakohen** [comment]
I do own a slice of server space in Europe that I use as a Seedbox. It runs plain jane linux so we could setup a nextcloud/owncloud deal or other variation. Thoughts? It has a 1Gbps link.

**Comment by ollieraikkonen** [comment]
@Drakohen ideally it needs to be a standard file server so we can download it with a https:// link directly without any sort of catchpa/login/"download now" buttons. If that will work then awesome

I *think* that the plugin supports mirrors. So we could add Github, your server and my server to spread the load and if one goes down it'll still work. Watch this space :)

**Comment by Drakohen** [comment]
Easy enough. I'll look into it next weekend and see what I can get spun up.

**Comment by BC46** [comment]
> I do own a slice of server space in Europe that I use as a Seedbox. It runs plain jane linux so we could setup a nextcloud/owncloud deal or other variation. Thoughts? It has a 1Gbps link.

Although a service that provides worldwide servers would be preferred, I think this would be a good option as a mirror for example.

**Comment by ollieraikkonen** [comment]
Note to self: The function to add a mirror is idpAddMirror. Sounds like if idbAddFileSize fails then it switches over to the mirror. You can add as many mirrors as you'd like

**Comment by ollieraikkonen** [comment]
Linode has been added
