### ISSUE TITLE
16:9 planetscapes don't install correctly

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#31]
Not 100% sure if this is correct since I don't exactly remember what option I checked last time.
Will update when I have more information.

**Comment by BC46** [comment]
My initial suspicions were correct. I left the option checked, and after installing the mod, all of the cityscape script files remain unchanged. Additionally, the 169.thn cityscape files are still in the destination directory, like nothing was done with them.

I think we may have forgotten to rename the original .thn files. The installer apparently can't rename a file when another file already exists with the same name.

**Comment by ollieraikkonen** [comment]
Yeah this wasn't changed after our discovery that you cant just rename to overwrite. Will fix

**Comment by ollieraikkonen** [comment]
It is likely missile effects are also affected

**Comment by ollieraikkonen** [comment]
Have fixed Effects and Planetscapes. Believe this could be an issue for the logos too. Leaving open for now
