### ISSUE TITLE
Incorrect defaults for several options

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#35]
- The current Startup Screen Resolution default is 960p 4:3. The actual default selected option should be 1080p 16:9.

- The current Freelancer Logo Resolution default is 600p 4:3. The actual default selected option should be 1080p 16:9. Additionally, this option should not be listed at the very top, but rather between 1080p 4:3 and 1440p 4:3.

- Single Player Command Console should be disabled by default as this option is not useful for everyone.

- The "Add new missile effects" was always disabled by default in the FLMM script since not everyone may like these. However, in the installer it's enabled by default. Should we leave it as is or disable it by default?

**Comment by ollieraikkonen** [comment]
I *think* I got confused by the (Default) label. Is it worth us renaming this to *Vanilla* ?

**Comment by BC46** [comment]
> I _think_ I got confused by the (Default) label. Is it worth us renaming this to _Vanilla_ ?

Yeah or maybe Vanilla default. Not sure what would be the best option.
