### ISSUE TITLE
GitHub link in Windows 10 compat option description not clickable

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#46]
Is it possible to make this link clickable?
![image](https://user-images.githubusercontent.com/45081813/137467429-f3c9b7d3-8117-4fbd-8e8c-7c4a0c847e2b.png)

**Comment by BC46** [comment]
If this is possible, change the link to https://github.com/BC46/freelancer-hd-edition/wiki/Windows-10-compatibility-patch-locks-FPS-or-refresh-rate-to-60

**Comment by ollieraikkonen** [comment]
Unfortunately this is not possible
