### ISSUE TITLE
Zoners 1-1 instead of Freelancer 1-1

### ISSUE THREAD

**Issue by ollieraikkonen** [ollieraikkonen/Freelancer-hd-edition-install-script#50]
User on reddit reported they are being called Zoners 1-1 instead of Freelancer 1-1. Need to check to see if there's an issue here or not.

**Comment by BC46** [comment]
That's really strange considering the string "gd_z", aka the faction name for Zoners, can't be found anywhere in the installation script. Could you ask the user if he could provide us his EXE/freelancer.ini file?

**Comment by ollieraikkonen** [comment]
@BC46 here's the reddit comment: https://www.reddit.com/r/freelancer/comments/qa1wmd/freelancer_hde_now_with_100_more_installer/hj4h15w/

**Comment by ollieraikkonen** [comment]
Yeah not sure how it could be the installer, if option 0 is selected we don't interact with it at all. Weird!

**Comment by BC46** [comment]
The user who reported this issue said it was caused by an edit he made to the mission triggers.
https://www.reddit.com/r/freelancer/comments/qa1wmd/comment/hjdegq4/?utm_source=share&utm_medium=web2x&context=3
