### ISSUE TITLE
.ini file converted to UTF-8 BOM

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#54]
A user had an issue where the dacom.ini file in EXE had 3 bytes added to the very start of the file which represents a UTF-8 BOM header. This essentially causes Freelancer to not be able to read the file.

![](https://media.discordapp.net/attachments/873144025350295617/908477346347106354/unknown.png)

This BOM header may be added by the installer while editing the .ini files. However, we haven't been able to prove that yet; there's a possibility that the issue lays somewhere completely else. Nevertheless, the actual source of the issue needs to be identified.

EDIT:
The issue has been identified. The BOM header gets added because of an option in Windows 10 called `Use Unicode UTF-8 for worldwide language support`. After enabling it, it interprets everything in programs as UTF-8 text or something like that.

You can find the option by going to Run (Win + R), type in `intl.cpl`, go to Administrative, and click `Change system locale...`.

**Comment by ollieraikkonen** [comment]
@BC46 have we had any other occurrences of this issue since early November?

**Comment by BC46** [comment]
Nope, that was the only ever occurrence as far as I know.

**Comment by BC46** [comment]
Coincidentally it just happened again today and I still have no idea how this is even possible.

**Comment by BC46** [comment]
I'm almost certain this is somehow done by the installer as it's always the dacom.ini, which is a file that the installer edits by default to enable the Adv Wide HUD.
