### ISSUE TITLE
Check for possibilities to remove read-only flags

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#57]
Some players encounter exceptions during the installation process because of files that are marked as read-only. It would be great if we could remove these read-only flags for all files that we overwrite.

**Comment by ollieraikkonen** [comment]
https://stackoverflow.com/questions/69159278/remove-read-only-attribute-from-existing-files-in-inno-setup?rq=1

**Comment by ollieraikkonen** [comment]
https://stackoverflow.com/questions/6122691/how-to-reset-file-attributes-with-filecopy

This seems to be how to do it. But I have reservations about using the WinAPI. We moved away from this with the unzipping to remain compatible with WINE. Will this work on WINE?

**Comment by ollieraikkonen** [comment]
Seems that you could detect WINE using: https://svistunov.dev/blog/2015/03/28/rasprostranenie-windows-prilojeniy-v-linux-wine-pri-pomoschi-innosetup-5

We could detect for WINE and skip using the WinAPI in this situation.

**Comment by BC46** [comment]
I was actually able to reproduce a crash by making Freelancer.exe read-only and running the installer as normally. 
![image](https://user-images.githubusercontent.com/45081813/152855428-f1d82d49-b944-409e-9732-daa569986078.png)

I can definitely imagine throwing an error for that is a bit overkill, especially considering the mod overwrites this file anyway. So we should really consider using that [SetFileAttributes](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesw) function in case the user is on Windows.

**Comment by ollieraikkonen** [comment]
Might be better to put the copying in a try/catch and store a log of what
failed to copy to display to the user at the end. As you said, most of the
time it wont matter anyway
