### ISSUE TITLE
Do not cancel installation after encountering a runtime error

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#59]

**Comment by ollieraikkonen** [comment]
@BC46 not sure about this one. If we allowed installs to complete after runtime errors this could lead to more complex issues (users have incorrect files). Could make it hard to debug user's issues. Are we sure we want to open that can of worms?

**Comment by BC46** [comment]
I'm actually not 100% sure either; it's just something I thought of when @Drakohen couldn't install the mod because of a few modified files in his Freelancer install that HDE overwrites anyway. If we actually choose to let he installation continue after hitting an exception, a log of errors needs to be shown at the end of the installation.

**Comment by BC46** [comment]
Not needed anymore.
