### ISSUE TITLE
Program uninstall entry missing icon

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#60]
![image](https://user-images.githubusercontent.com/45081813/147083927-8679c43e-0e59-4a2e-a25d-f5e61793b4fb.png)
When uninstalling a program in Windows 10, you can see that the entry for the installer is missing an icon.

**Comment by ollieraikkonen** [comment]
![image](https://user-images.githubusercontent.com/40522943/147123995-b90a4920-deb7-4e05-b465-ee33fe5e28b3.png)
