### ISSUE TITLE
Many redundant files left behind after installation

### ISSUE THREAD

**Issue by BC46** [ollieraikkonen/Freelancer-hd-edition-install-script#81]
![image](https://user-images.githubusercontent.com/45081813/160808017-6fd49eba-1622-4dfa-9df2-b5ad66e2a612.png)
I'd say the following files are redundant:
- installinfo.txt
- All `.dll` files from 2003
- All `.msi` files from 2003

**Comment by ollieraikkonen** [comment]
Fixed
